import { defineConfig, mergeConfig } from 'vitest/config';
import { fileURLToPath, URL } from 'node:url';
import viteConfig from './vite.config';
import { resourceLoaderCommonJs } from './tests/RedHerb/resourceLoaderCommonJs';

const redHerbResources = fileURLToPath( new URL( '../../tests/RedHerb/resources', import.meta.url ) );
const publicApi = fileURLToPath( new URL( './src/public-api.ts', import.meta.url ) );

export default mergeConfig( viteConfig, defineConfig( {
	plugins: [
		resourceLoaderCommonJs( {
			sourceDir: redHerbResources,
			resolveFrom: publicApi,
			providedModules: {
				vue: 'vue',
				'ext.neowiki': publicApi,
				// Generated by CodexModule, so they exist only at runtime.
				'./codex.js': '@wikimedia/codex',
				'./icons.json': '@wikimedia/codex-icons',
			},
		} ),
	],
	resolve: {
		alias: {
			'@redherb': redHerbResources,
		},
	},
	test: {
		environment: 'jsdom',
		globals: true,
		coverage: {
			provider: 'v8',
			include: [ 'src' ],
			reporter: [ 'text', 'json-summary', 'json' ],
			reportOnFailure: true,
		},
	},
} ) );
