-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/neowiki_rebuild_runs.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE neowiki_rebuild_runs (
  nwrr_id SERIAL NOT NULL,
  nwrr_store TEXT NOT NULL,
  nwrr_status TEXT NOT NULL,
  nwrr_phase TEXT DEFAULT 'pages' NOT NULL,
  nwrr_cursor INT DEFAULT 0 NOT NULL,
  nwrr_processed INT DEFAULT 0 NOT NULL,
  nwrr_failed INT DEFAULT 0 NOT NULL,
  nwrr_trigger TEXT NOT NULL,
  nwrr_started TIMESTAMPTZ NOT NULL,
  nwrr_finished TIMESTAMPTZ DEFAULT NULL,
  nwrr_error TEXT DEFAULT NULL,
  PRIMARY KEY(nwrr_id)
);

CREATE INDEX nwrr_store_started ON neowiki_rebuild_runs (nwrr_store, nwrr_started);
