-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-neowiki_rebuild_runs-nwrr_phase.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE neowiki_rebuild_runs
  ADD nwrr_phase TEXT DEFAULT 'pages' NOT NULL;
