-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-neowiki_subject_page-subject-header.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE neowiki_subject_page
  ADD nwsp_schema TEXT DEFAULT NULL;
ALTER TABLE neowiki_subject_page
  ADD nwsp_label TEXT DEFAULT NULL;
ALTER TABLE neowiki_subject_page
  ADD nwsp_is_main SMALLINT DEFAULT 0 NOT NULL;
