-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/neowiki_rebuild_runs.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/neowiki_rebuild_runs (
  nwrr_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  nwrr_store BLOB NOT NULL, nwrr_status BLOB NOT NULL,
  nwrr_phase BLOB DEFAULT 'pages' NOT NULL,
  nwrr_cursor INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  nwrr_processed INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  nwrr_failed INTEGER UNSIGNED DEFAULT 0 NOT NULL,
  nwrr_trigger BLOB NOT NULL, nwrr_started BLOB NOT NULL,
  nwrr_finished BLOB DEFAULT NULL, nwrr_error BLOB DEFAULT NULL
);

CREATE INDEX nwrr_store_started ON /*_*/neowiki_rebuild_runs (nwrr_store, nwrr_started);
