-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/neowiki_subject_page.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/neowiki_subject_page (
  nwsp_subject_id BLOB NOT NULL,
  nwsp_page_id INTEGER UNSIGNED NOT NULL,
  nwsp_schema BLOB DEFAULT NULL,
  nwsp_label BLOB DEFAULT NULL,
  nwsp_is_main SMALLINT UNSIGNED DEFAULT 0 NOT NULL,
  PRIMARY KEY(nwsp_subject_id, nwsp_page_id)
);

CREATE INDEX nwsp_page_id ON /*_*/neowiki_subject_page (nwsp_page_id);
