-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-neowiki_subject_page-subject-header.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/neowiki_subject_page
  ADD COLUMN nwsp_schema BLOB DEFAULT NULL;
ALTER TABLE /*_*/neowiki_subject_page
  ADD COLUMN nwsp_label BLOB DEFAULT NULL;
ALTER TABLE /*_*/neowiki_subject_page
  ADD COLUMN nwsp_is_main SMALLINT UNSIGNED DEFAULT 0 NOT NULL;
