-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/neowiki_rebuild_runs.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/neowiki_rebuild_runs (
  nwrr_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  nwrr_store VARBINARY(255) NOT NULL,
  nwrr_status VARBINARY(32) NOT NULL,
  nwrr_phase VARBINARY(32) DEFAULT 'pages' NOT NULL,
  nwrr_cursor INT UNSIGNED DEFAULT 0 NOT NULL,
  nwrr_processed INT UNSIGNED DEFAULT 0 NOT NULL,
  nwrr_failed INT UNSIGNED DEFAULT 0 NOT NULL,
  nwrr_trigger VARBINARY(32) NOT NULL,
  nwrr_started BINARY(14) NOT NULL,
  nwrr_finished BINARY(14) DEFAULT NULL,
  nwrr_error BLOB DEFAULT NULL,
  INDEX nwrr_store_started (nwrr_store, nwrr_started),
  PRIMARY KEY(nwrr_id)
) /*$wgDBTableOptions*/;
