-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/abstractSchemaChanges/patch-neowiki_subject_page-subject-header.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/neowiki_subject_page
  ADD nwsp_schema VARBINARY(255) DEFAULT NULL,
  ADD nwsp_label BLOB DEFAULT NULL,
  ADD nwsp_is_main TINYINT UNSIGNED DEFAULT 0 NOT NULL;
